spring:
  datasource:
    url: jdbc:h2:mem:dummydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
